#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Simple clear command
alias c='clear'

# Use htop in place of top
alias top='htop'

#
# Some OS X-only stuff
#

if [[ "$OSTYPE" == darwin* ]]; then
  # Remove all items safely, to Trash (`brew install trash`)
  alias rm='trash'
fi
